name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cache node.js modules
        uses: actions/cache@v2
        id: cache
        with:
          path: ./frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Lint
        run: npm run lint
        working-directory: ./frontend

      - name: Test
        run: npm run test
        working-directory: ./frontend
